### ISSUE TITLE
สร้าง GitHub actions สำหรับรัน static analysis & tests

### ISSUE THREAD

**Issue by zkan** [dataength/heimdall#21]
GitHub actions สำหรับ static analysis & tests เพื่อควบคุม code quality

**Comment by heyfirst** [comment]
May I pick this up? 😄 Creating 2 actions for backend and frontend

Frontend
- eslint setup for static analysis
- simple react-testing-library for UI integration test

Backend
- (black/flake8) for static analysis /TBC @zkan @atbee please select your preference, I have no idea on this point naaa
- django test command with postgresdb setup.

PS. Only 9 days left and I have no PR yet 😭

**Comment by zkan** [comment]
@heyfirst Cool! Go for it! 🔥

Let's use Flake8. Black is for code formatting and we can run it on our local machine before commit.
